config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  
  resources :posts do
      resources :comments
  end
  

  get 'tags/:tag', to: 'posts#index',  as: :tag

  
  resources :users, :only => [:show]
  devise_for :users, :path_prefix => 'd', :controllers => { :omniauth_callbacks => "callbacks", registrations: 'registrations' }

  root 'posts#index'

end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
  validates :title, presence: true,
                    length: { minimum: 5 }
  acts_as_taggable_on :tags
  def to_param
    "#{id} #{title}".parameterize
  end


  extend FriendlyId
  friendly_id :title, use: :slugged

  def should_generate_new_friendly_id?
    new_record?
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
     :omniauthable, :omniauth_providers => [:facebook]


  def self.from_omniauth(auth)
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.password = Devise.friendly_token[0,20]
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])

    @comment = @post.comments.create(comment_params)
    
    # redirect_to post_path(@post)
     respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@post), notice: 'Comment was successfully updated.' }
        format.js   { }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @post = Post.find(params[:post_id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:commenter, :body, :post_id)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new,:update,:destroy]

  # GET /posts
  # GET /posts.json
  def index
    if params[:tag]
      @posts = Post.tagged_with(params[:tag]).page(params[:page]).per(10)
    else
      @posts = Post.order('id DESC').page(params[:page]).per(10)
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
        if request.path != post_path(@post)
    redirect_to @post, status: :moved_permanently
  end
  end

  # GET /posts/new
  def new
    @post = current_user.posts.new
  end

  # GET /posts/1/edit
  def edit

  end

  def all_comments
    parent_comments = Comment.where(:commentable_id => id)
    child_comments = Comment.where(:commentable_id => parent_comments.map(&:id))
    parent_comments + child_comments
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)
    
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.js   { }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.js   { }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to current_user }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :author_name)
    end

    def post_params
      params.require(:post).permit(:title, :body, :author_name, :tag_list)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  after_action :remove_notice, only: :destroy

  private

  def remove_notice
    flash[:notice] = nil
  end

  private

  def sign_up_params
    params.require(:user).permit(:name, :bio, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :bio, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController
  after_action :remove_notice, only: :destroy

  private

  def remove_notice
    flash[:notice] = nil
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	def show
	  @user = User.find(params[:id])
	  @post = Post.joins(:user).where(user_id: params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
                    <h2><%= @post.comments.count %> Comments</h2>
                    <p>Reply Comment</p>
                          <% @post.comments.each do |comment| %>
                        <div class="catagerious">
                            <div class="col-md-5 catagerious1">
                              <div class="catagerious-left">
                                <h4><a href="#"><%= comment.commenter %></a></h4>
                                <p><%= comment.created_at.strftime('%b %d, %Y') %></p>
                              </div>
                                
                            </div>
                            <div class="col-md-7 catagerious2">
                              <h4><%= comment.body %></h4>
                              <h6><%= link_to 'Delete Comment', [comment.post, comment],
                                    method: :delete, data: { confirm: 'Are you sure?' } %></h6>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                    <% end %>
                    <%= form_for([@post, @post.comments.build], remote: true)  do |f| %> 
                  <div class="col-md-6 contact">
                  <h3>Add a Comment : </h3>
                    <form>
                        <% if user_signed_in? %>
                             <%= f.text_field :commenter , :class => 'text' ,:value => current_user.name, :required => true, placeholder: "Enter your name" %>
                        <% else %>
                             <%= f.text_field :commenter , :class => 'text', :required => true %>
                        <% end %>
                              <%= f.text_area :body, rows: 10 %>
                               <%= f.submit :id => 'submit' %>
                        <% end %>
                    </form>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.text_field :post_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$(".comments").html("<%= escape_javascript(render("comment")) %>");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Commenter</th>
      <th>Body</th>
      <th>Post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.commenter %></td>
        <td><%= comment.body %></td>
        <td><%= comment.post %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Commenter:</strong>
  <%= @comment.commenter %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Post:</strong>
  <%= @comment.post %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>   
  <html>   
  <head>   
    <title>Rylai Blog</title>   
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>   
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>   
    <%= csrf_meta_tags %>   
  </head>   
  <body>   
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">   
       <div class="container">   
         <div class="navbar-header">   
            <%= link_to "Rylai Blog", posts_path , class: 'navbar-brand' %>
      <!--       <a class="navbar-brand" href="#">Rylai Blog</a>   --> 
         </div>   
         <ul class="nav navbar-nav">    
         </ul>   
         <ul class="nav navbar-nav navbar-right">   
            <% if user_signed_in? %>   
            <li><%= link_to current_user.name, current_user %></li>   
            <li><%= link_to "New Post" , new_post_path  %></li>   
            <li><%= link_to "Log Out" , destroy_user_session_path, method: :delete %></li>
            <% else %>   
            <li><%= link_to "Sign In", user_session_path %></li>   
            <li><%= link_to "Register", new_user_registration_path %></li>   
            <% end %>   
         </ul>   
       </div>   
    </div>   
    <div class="container">   
       <%= yield %>   
    </div>   
      <%= yield :javascript_in_body %>
  </body>   
  </html>   

app/views/posts/_comment.html.erb
                    <h2><%= @post.comments.count %> Comments</h2>
                    <p>Reply Comment</p>
                          <% @post.comments.each do |comment| %>
                        <div class="catagerious">
                            <div class="col-md-5 catagerious1">
                              <div class="catagerious-left">
                                <h4><a href="#"><%= comment.commenter %></a></h4>
                                <p><%= comment.created_at.strftime('%b %d, %Y') %></p>
                              </div>
                                
                            </div>
                            <div class="col-md-7 catagerious2">
                              <h4><%= comment.body %></h4>
                              <h6><a href="#">Reply</a></h6>
                            </div>
                            <div class="clearfix"> </div>
                        </div>
                        <% end %>
                   <%= form_for([@post, @post.comments.build], remote: true)  do |f| %> 
                  <div class="col-md-6 contact">
                  <h3>Add a Comment : </h3>
                    <form>
                        <% if user_signed_in? %>
                             <%= f.text_field :commenter , :class => 'text' ,:value => current_user.name, :required => true, placeholder: "Enter your name" %>
                        <% else %>
                             <%= f.text_field :commenter , :class => 'text', :required => true %>
                        <% end %>
                        <%= f.text_area :body, rows: 10 %>
                         <%= f.submit :id => 'submit' %>
                        <% end %>
                    </form>
                  </div>
                <div class="clearfix"> </div>

app/views/posts/_form.html.erb
<% if user_signed_in? %>
        <%= form_for(@post) do |f| %>
          <% if @post.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
              <ul>
              <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

          <div class="field">
            <%= f.label :title %><br>
            <%= f.text_field :title, :class => 'form-control' %>
          </div>
          <div class="field" style="padding-right:500px;">
            <%= f.label :body %><br>
            <%= f.cktext_area :body, :class => 'form-control'%>
          </div>
          <div class="input-row">
            <%= f.label :tags %>
            <%= f.text_field :tag_list %>
          </div>
          <div class="field">
            <%= f.label :author_name %><br>
            <%= f.text_field :author_name , :value => current_user.name %>
          </div>
          <div class="actions">
            <%= f.submit %>
          </div>
        <% end %>
<% else %>
      <p>You must login </p>
<% end %>


  <% content_for :javascript_in_body do %>
  <%= javascript_tag do %>
    $(document).ready(function(){
       $('.input-row #post_topics_list, .input-row #post_tags_list').select2({tags: true})
    });
  <% end %>
  <% end %>

app/views/posts/comment.js.erb
$("comments").html("<%= escape_javascript(render("comment")) %>");

app/views/posts/create.js.erb
$("#comments").html("<%=j render(comments/comment) %>");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,800,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<script src="js/jquery.min.js"></script>                
</head>
<body>
<!-- header -->
    <div class="banner">
        <div class="container">
            <div class="logo">
                <a href="#"><img src="/images/logo.png" class="img-responsive" alt="" /></a>
            </div>
        </div> 
            <div class="header-bottom">
                <div class="container">
                    <div class="head-nav">
                        <span class="menu"> </span>
                            <ul>
                                <li class="active"><%= link_to 'Home', posts_path %></li>
                                <li><a href="#">About</a></li>
                                <li><a href="#">Categories</a></li>
                                <div class="clearfix"> </div>
                        </ul>
                </div>
                <!-- script-for-nav -->
                    <script>
                        $( "span.menu" ).click(function() {
                          $( ".head-nav ul" ).slideToggle(300, function() {
                            // Animation complete.
                          });
                        });
                    </script>
                <!-- script-for-nav -->     
                    <div class="search-box">
                        <form>
                            <input type="text" name="s" class="textbox" value="search something" onfocus="this.value = '';" onblur="if
                                    (this.value == '') {this.value = 'search something';}">
                            <input type="submit" value>
                        </form>
                    </div>
                        <div class="clearfix"> </div>
                </div>
            </div>
    </div>
<!-- header -->
<!-- content -->
    <div class="container">
        <div class="content">
         <% @posts.each do |post| %>
    <div class="travelling">
            <div class="col-md-10 travelling1">
                <h1><%= link_to post.title, post %></h1>
                <h5>by <%= post.author_name %>,
                </a> <%= post.created_at.strftime('%b %d, %Y') %>
               , Tags: <%= raw post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %></h5>
                <p><%= raw post.body.truncate(480) %></p>
            </div>
            <div class="col-md-1 travelling2">
                <h3><%= post.comments.count %></h3>
                <a href="#">comments</a>
            </div>
                <div class="clearfix"> </div>
        </div>
    <% end %>
        <center>
            <div class="pagination">
                <%= paginate @posts %>
                <%= page_entries_info @posts %>
            </div>
        </center>
    </div>
</div>

<!-- content -->
<!-- footer -->
    <div class="footer">
        <div class="container">
            <p>Template by <a href="http://w3layouts.com" target="_blank"> w3layouts</a></p>
            <div class="social">
                <ul>
                    <li><a href="#"><i class="fb"> </i></li></a>
                    <li><a href="#"><i class="twt"> </i></li></a>
                        <div class="clearfix"></div>
                </ul>
            </div>
        </div>
    </div>
<!-- footer -->
</body>
</html>

app/views/posts/index.js.erb
$(".comments").html("<%= escape_javascript(render("comment")) %>");

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/post.js.erb
$(".comments").html("<%= escape_javascript(render("comment")) %>");

app/views/posts/show.html.erb
<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,800,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<script src="js/jquery.min.js"></script>
</head>
<body>
<!-- header -->
  <div class="banner">
        <div class="container">
      <div class="logo">
        <a href="index.html"><img src="/images/logo.png" class="img-responsive" alt="" /></a>
      </div>
    </div> 
      <div class="header-bottom">
        <div class="container">
          <div class="head-nav">
            <span class="menu"> </span>
              <ul>
                <li><%= link_to 'Home', posts_path %></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Categories</a></li>
                <div class="clearfix"> </div>
            </ul>
        </div>
        <!-- script-for-nav -->
          <script>
            $( "span.menu" ).click(function() {
              $( ".head-nav ul" ).slideToggle(300, function() {
              // Animation complete.
              });
            });
          </script>
        <!-- script-for-nav -->   
          <div class="search-box">
                <form>
                    <input type="text" name="s" class="textbox" value="search something" onfocus="this.value = '';" onblur="if
                            (this.value == '') {this.value = 'search something';}">
                    <input type="submit" value>
                </form>
                </div>
            <div class="clearfix"> </div>
        </div>
      </div>
  </div>
<!-- header -->
<!-- content -->
  <div class="container">
    <div class="content">
      <a href="#"></a>
        <div class="travelling">
          <div class="col-md-10 travelling1">
            <h1><a href="#"><%= @post.title %></a></h1>
            <h5>by <a href="#"><%= @post.author_name %> ,</a> <%= @post.created_at.strftime('%b %d, %Y') %>
            , Tags: <%= raw @post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>,</h5>
            <h5><%= social_share_button_tag(@post.title, url: 'https://blooming-river-52711.herokuapp.com/', popup: true) %></h5>
          </div>
            <div class="clearfix"> </div>
             <p><%= raw @post.body %></p>
               <div id="comments">
                   
               </div>
                  <div class="comments">  
                      <%= render 'comments/comment' %>
                  </div>
                <div class="clearfix"> </div>
            </div>
          </div>
       </div>  
  </div>
<!-- content -->
<!-- footer -->
  <div class="footer">
    <div class="container">
      <p>Template by <a href="http://w3layouts.com" target="_blank"> w3layouts</a></p>
      <div class="social">
        <ul>
          <li><a href="#"><i class="fb"> </i></li></a>
          <li><a href="#"><i class="twt"> </i></li></a>
            <div class="clearfix"></div>
        </ul>
      </div>
    </div>
  </div>
<!-- footer -->
</body>
</html>

app/views/posts/untitled.js.erb
$('.contact').html("<%= escape_javascript render(@comment) %>");

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta content="IE=edge" http-equiv="X-UA-Compatible" />
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,800,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
    <title>IMDB</title>
    <!-- LINK CALL -->
    <link href="css/bootstrap.min.css" rel="stylesheet" />
    <link href="css/custom.min.css" rel="stylesheet" />
  </head>
  <body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
    <div class="container custom-profile">
      <div class="row">
        <div class="col-md-4 custom-side">

          <img src="http://placehold.it/300x350?text=1" class="img-rounded img-responsive thumbnail">
          <hr style="width:5px;height:2px;background:white;">
          <blockquote>
                <h1><%= @user.name %></h1>
          </blockquote>
                <p>
                <i class="glyphicon glyphicon-envelope" style="color:#FF6000; padding-right:5px;"></i><%= current_user.email %>
                <br>
                <p>"<%= @user.bio %>"</p>
        </div>
        <div class="col-md-8  custom-recent">
        <div class="container-fluid">
                <h1 style="border-bottom:solid 2px #FF6000;">Recent Post</h1>
                  <div class="row">
                  <% @post.each do |post| %>
                    <div class="col-md-12 custom-post"><br>
                      <h2><%= post.title %></h2>
                      <h4><%= raw post.body %></h4>
                        <% if current_user.id == post.user_id %>
                      <%= link_to 'Update', edit_post_path(post), class: 'btn-custom-edit' %> 
                      <%= link_to 'Destroy', post, class: 'btn-custom-delete', method: :delete, data: { confirm: 'Are you sure?' } %>
                       <%= link_to 'Read More', post, class: 'btn-custom-readmore' %> 
                        <% else %>
                        <!-- NONE -->
                        <% end %>
                      </div>
                    <% end %>
                  </div>
                </div>
        </div>
      </div>
    </div>
    <!-- jQuery -->
    <script src="js/jquery.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>
    <!-- Plugin JavaScript -->
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js"></script>

  </body>
</html>